# Generated by Django 5.0.3 on 2024-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_property_description_property_postcode_property_ppw"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_pcm",
            field=models.IntegerField(),
        ),
    ]
