# Generated by Django 5.0.3 on 2024-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='num_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
