# Generated by Django 5.0.3 on 2024-04-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_num_bathrooms_property_num_beds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='num_bathrooms',
            new_name='number_of_bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='num_beds',
            new_name='number_of_beds',
        ),
    ]
