# Generated by Django 5.0.3 on 2024-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_countries_property_city_property_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="image",
            new_name="image1",
        ),
        migrations.AddField(
            model_name="property",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="prop_images"),
        ),
        migrations.AddField(
            model_name="property",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="prop_images"),
        ),
        migrations.AddField(
            model_name="property",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="prop_images"),
        ),
    ]
