# Generated by Django 5.0.3 on 2024-04-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_image_property_image1_property_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ppw',
            new_name='PPW',
        ),
    ]
