# Generated by Django 5.0.3 on 2024-04-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_category_options_rename_ppw_property_ppw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_pcm',
            new_name='price_PCM',
        ),
    ]
